version: '3.8'

services:
  node:
    image: node:lts-slim
    working_dir: /app
    env_file:
      - .env
    command: /bin/sh -c 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]  # Utiliser le nom du service 'db'
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Utilisé pour le mot de passe root
    volumes:
      - ./db:/var/lib/mysql
      # - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Utiliser si tu as un script d'initialisation

  db_test:
    image: mysql:8.0
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]  # Utiliser le nom du service 'db'
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}  # Utilisé pour le mot de passe root
    volumes:
      - ./db_test:/var/lib/mysql
      # - ./sql/test.sql:/docker-entrypoint-initdb.d/test.sql  # Utiliser si tu as un script d'initialisation

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
