version: '3.8'

services:
  auth-db:
    build: 
      context: ./service-auth
      dockerfile: docker/mysql/Dockerfile 
    container_name: auth-db
    env_file:
      - ./service-auth/.env
    restart: always
    volumes: 
      - ./service-auth/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"

  users-db:
    image: mysql:8.0
    container_name: users-db
    env_file:
      - ./service-users/.env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./service-users/data:/var/lib/mysql
    ports:
      - "3308:3306"

  products-db:
    build: 
      context: ./service-products
      dockerfile: docker/mysql/Dockerfile 
    container_name: products-db
    env_file:
      - ./service-products/.env
    restart: always 
    volumes: 
      - ./service-products/data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "3309:3306"

  paiment-db:
    image: mariadb:lts
    container_name: paiment-db
    env_file:
      - ./service-paiment/.env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./service-paiment/data:/var/lib/mysql
    ports: 
      - "3310:3306"

  paiment-db-test:
    image: mariadb:lts
    container_name: paiment-db-test
    env_file:
      - ./service-paiment/.env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      timeout: 10s
    environment:
      MYSQL_DATABASE: ${DB_NAME_TEST}
      MYSQL_USER: ${DB_USER_TEST}
      MYSQL_PASSWORD: ${DB_PASSWORD_TEST}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./service-paiment/test-data:/var/lib/mysql
    ports: 
      - "3311:3306"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - service-auth
      - service-users
      - service-products
      - service-paiment

  service-auth:
    build:
      context: ./service-auth
      dockerfile: docker/node/Dockerfile
    container_name: service-auth
    volumes:
      - ./service-auth:/home/node/app
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    env_file:
      - ./service-auth/.env

  service-users:
    build:
      context: ./service-users
      dockerfile: docker/node/Dockerfile
    container_name: service-users
    volumes:
      - ./service-users:/home/node/app
    ports:
      - "3002:3002"
    depends_on:
      - users-db
    env_file:
      - ./service-users/.env

  service-products:
    build:
      context: ./service-products
      dockerfile: docker/node/Dockerfile
    container_name: service-products
    volumes:
      - ./service-products:/home/node/app
    ports:
      - "3003:3003"
    depends_on:
      - products-db
    env_file:
      - ./service-products/.env

  service-paiment:
    build:
      context: ./service-paiment
      dockerfile: docker/node/Dockerfile
    container_name: service-paiment
    volumes:
      - ./service-paiment:/home/node/app
    ports:
      - "3005:3005"
    depends_on:
      - paiment-db
    env_file:
      - ./service-paiment/.env