version: '3'

services: 

  db: 
    build: 
      context: ./ 
      dockerfile: docker/mysql/Dockerfile 
    container_name: db 
    restart: always 
    volumes: 
      - ./db:/data/db 
    ports: 
      - "3306:3306" 
    environment: 
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1

  app: 
    build: 
      context: ./ 
      dockerfile: docker/node/Dockerfile 
    container_name: node-app 
    volumes: 
      - ./api:/home/node/app/api 
    ports: 
      - "3002:3002" 
    depends_on: 
      - db 
    env_file: 
      - .env