version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commandes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  service-commands:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    entrypoint: ["sh", "-c", "while ! nc -z db 3306; do sleep 1; done; node api/src/app.js"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
