version: '3'

services: 

  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db:/var/lib/mysql

  db_test:
    image: mariadb:lts
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    environment:
      MYSQL_DATABASE: ${DB_NAME_TEST}
      MYSQL_USER: ${DB_USER_TEST}
      MYSQL_PASSWORD: ${DB_PASSWORD_TEST}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db_test:/var/lib/mysql


  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1

  app: 
    build: 
      context: ./ 
      dockerfile: docker/node/Dockerfile 
    container_name: node-app 
    volumes: 
      - ./api:/home/node/app/api 
    ports: 
      - "3010:3010" 
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env